/* tslint:disable */
/* eslint-disable */
/**
 * Binance USD-M Futures API
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetPositionRiskV2RespItem
 */
export interface GetPositionRiskV2RespItem {
    /**
     * 
     * @type {string}
     * @memberof GetPositionRiskV2RespItem
     */
    'breakEvenPrice'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionRiskV2RespItem
     */
    'entryPrice'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionRiskV2RespItem
     */
    'isAutoAddMargin'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionRiskV2RespItem
     */
    'isolatedMargin'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionRiskV2RespItem
     */
    'isolatedWallet'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionRiskV2RespItem
     */
    'leverage'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionRiskV2RespItem
     */
    'liquidationPrice'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionRiskV2RespItem
     */
    'marginType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionRiskV2RespItem
     */
    'markPrice'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionRiskV2RespItem
     */
    'maxNotionalValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionRiskV2RespItem
     */
    'notional'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionRiskV2RespItem
     */
    'positionAmt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionRiskV2RespItem
     */
    'positionSide'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionRiskV2RespItem
     */
    'symbol'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionRiskV2RespItem
     */
    'unRealizedProfit'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetPositionRiskV2RespItem
     */
    'updateTime'?: number;
}

