/* tslint:disable */
/* eslint-disable */
/**
 * Binance USD-M Futures API
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetMultiAssetsMarginV1Resp
 */
export interface GetMultiAssetsMarginV1Resp {
    /**
     * 
     * @type {boolean}
     * @memberof GetMultiAssetsMarginV1Resp
     */
    'multiAssetsMargin'?: boolean;
}

