/* tslint:disable */
/* eslint-disable */
/**
 * Binance USD-M Futures API
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetApiReferralTradeVolV1RespItem
 */
export interface GetApiReferralTradeVolV1RespItem {
    /**
     * 
     * @type {number}
     * @memberof GetApiReferralTradeVolV1RespItem
     */
    'time'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetApiReferralTradeVolV1RespItem
     */
    'tradeVol'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetApiReferralTradeVolV1RespItem
     */
    'unit'?: string;
}

