/* tslint:disable */
/* eslint-disable */
/**
 * Binance USD-M Futures API
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetIncomeV1RespItem
 */
export interface GetIncomeV1RespItem {
    /**
     * 
     * @type {string}
     * @memberof GetIncomeV1RespItem
     */
    'asset'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetIncomeV1RespItem
     */
    'income'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetIncomeV1RespItem
     */
    'incomeType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetIncomeV1RespItem
     */
    'info'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetIncomeV1RespItem
     */
    'symbol'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetIncomeV1RespItem
     */
    'time'?: number;
}

