/* tslint:disable */
/* eslint-disable */
/**
 * Binance USD-M Futures API
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetFuturesDataTakerlongshortRatioRespItem
 */
export interface GetFuturesDataTakerlongshortRatioRespItem {
    /**
     * 
     * @type {string}
     * @memberof GetFuturesDataTakerlongshortRatioRespItem
     */
    'buySellRatio'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFuturesDataTakerlongshortRatioRespItem
     */
    'buyVol'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFuturesDataTakerlongshortRatioRespItem
     */
    'sellVol'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFuturesDataTakerlongshortRatioRespItem
     */
    'timestamp'?: string;
}

