/* tslint:disable */
/* eslint-disable */
/**
 * Binance USD-M Futures API
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetIndexInfoV1RespItemBaseAssetListInner } from './get-index-info-v1-resp-item-base-asset-list-inner';

/**
 * 
 * @export
 * @interface GetIndexInfoV1RespItem
 */
export interface GetIndexInfoV1RespItem {
    /**
     * 
     * @type {Array<GetIndexInfoV1RespItemBaseAssetListInner>}
     * @memberof GetIndexInfoV1RespItem
     */
    'baseAssetList'?: Array<GetIndexInfoV1RespItemBaseAssetListInner>;
    /**
     * 
     * @type {string}
     * @memberof GetIndexInfoV1RespItem
     */
    'component'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetIndexInfoV1RespItem
     */
    'symbol'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetIndexInfoV1RespItem
     */
    'time'?: number;
}

