/* tslint:disable */
/* eslint-disable */
/**
 * Binance USD-M Futures API
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UmfuturesGetExchangeInfoV1RespRateLimitsInner
 */
export interface UmfuturesGetExchangeInfoV1RespRateLimitsInner {
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetExchangeInfoV1RespRateLimitsInner
     */
    'interval'?: string;
    /**
     * 
     * @type {number}
     * @memberof UmfuturesGetExchangeInfoV1RespRateLimitsInner
     */
    'intervalNum'?: number;
    /**
     * 
     * @type {number}
     * @memberof UmfuturesGetExchangeInfoV1RespRateLimitsInner
     */
    'limit'?: number;
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetExchangeInfoV1RespRateLimitsInner
     */
    'rateLimitType'?: string;
}

