/* tslint:disable */
/* eslint-disable */
/**
 * Binance USD-M Futures API
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UmfuturesGetAggTradesV1RespItem
 */
export interface UmfuturesGetAggTradesV1RespItem {
    /**
     * 
     * @type {number}
     * @memberof UmfuturesGetAggTradesV1RespItem
     */
    'T'?: number;
    /**
     * 
     * @type {number}
     * @memberof UmfuturesGetAggTradesV1RespItem
     */
    'a'?: number;
    /**
     * 
     * @type {number}
     * @memberof UmfuturesGetAggTradesV1RespItem
     */
    'f'?: number;
    /**
     * 
     * @type {number}
     * @memberof UmfuturesGetAggTradesV1RespItem
     */
    'l'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UmfuturesGetAggTradesV1RespItem
     */
    'm'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetAggTradesV1RespItem
     */
    'p'?: string;
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetAggTradesV1RespItem
     */
    'q'?: string;
}

