/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateBrokerSubAccountApiCommissionV1Resp
 */
export interface CreateBrokerSubAccountApiCommissionV1Resp {
    /**
     * 
     * @type {number}
     * @memberof CreateBrokerSubAccountApiCommissionV1Resp
     */
    'makerCommission'?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateBrokerSubAccountApiCommissionV1Resp
     */
    'marginMakerCommission'?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateBrokerSubAccountApiCommissionV1Resp
     */
    'marginTakerCommission'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateBrokerSubAccountApiCommissionV1Resp
     */
    'subAccountId'?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateBrokerSubAccountApiCommissionV1Resp
     */
    'takerCommission'?: number;
}

