/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateMarginOrderOcoV1RespOrdersInner
 */
export interface CreateMarginOrderOcoV1RespOrdersInner {
    /**
     * 
     * @type {string}
     * @memberof CreateMarginOrderOcoV1RespOrdersInner
     */
    'clientOrderId'?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateMarginOrderOcoV1RespOrdersInner
     */
    'orderId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateMarginOrderOcoV1RespOrdersInner
     */
    'symbol'?: string;
}

