/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeleteAlgoFuturesOrderV1Resp
 */
export interface DeleteAlgoFuturesOrderV1Resp {
    /**
     * 
     * @type {number}
     * @memberof DeleteAlgoFuturesOrderV1Resp
     */
    'algoId'?: number;
    /**
     * 
     * @type {number}
     * @memberof DeleteAlgoFuturesOrderV1Resp
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof DeleteAlgoFuturesOrderV1Resp
     */
    'msg'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DeleteAlgoFuturesOrderV1Resp
     */
    'success'?: boolean;
}

