/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetLoanFlexibleOngoingOrdersV2RespRowsInner } from './get-loan-flexible-ongoing-orders-v2-resp-rows-inner';

/**
 * 
 * @export
 * @interface GetLoanFlexibleOngoingOrdersV2Resp
 */
export interface GetLoanFlexibleOngoingOrdersV2Resp {
    /**
     * 
     * @type {Array<GetLoanFlexibleOngoingOrdersV2RespRowsInner>}
     * @memberof GetLoanFlexibleOngoingOrdersV2Resp
     */
    'rows'?: Array<GetLoanFlexibleOngoingOrdersV2RespRowsInner>;
    /**
     * 
     * @type {number}
     * @memberof GetLoanFlexibleOngoingOrdersV2Resp
     */
    'total'?: number;
}

