/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetAssetWalletBalanceV1RespItem
 */
export interface GetAssetWalletBalanceV1RespItem {
    /**
     * 
     * @type {boolean}
     * @memberof GetAssetWalletBalanceV1RespItem
     */
    'activate'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetAssetWalletBalanceV1RespItem
     */
    'balance'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAssetWalletBalanceV1RespItem
     */
    'walletName'?: string;
}

