/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetSubAccountFuturesPositionRiskV2RespFuturePositionRiskVosInner
 */
export interface GetSubAccountFuturesPositionRiskV2RespFuturePositionRiskVosInner {
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesPositionRiskV2RespFuturePositionRiskVosInner
     */
    'entryPrice'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesPositionRiskV2RespFuturePositionRiskVosInner
     */
    'leverage'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesPositionRiskV2RespFuturePositionRiskVosInner
     */
    'liquidationPrice'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesPositionRiskV2RespFuturePositionRiskVosInner
     */
    'markPrice'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesPositionRiskV2RespFuturePositionRiskVosInner
     */
    'maxNotional'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesPositionRiskV2RespFuturePositionRiskVosInner
     */
    'positionAmount'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesPositionRiskV2RespFuturePositionRiskVosInner
     */
    'symbol'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesPositionRiskV2RespFuturePositionRiskVosInner
     */
    'unrealizedProfit'?: string;
}

