/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetSubAccountUniversalTransferV1RespResultInner } from './get-sub-account-universal-transfer-v1-resp-result-inner';

/**
 * 
 * @export
 * @interface GetSubAccountUniversalTransferV1Resp
 */
export interface GetSubAccountUniversalTransferV1Resp {
    /**
     * 
     * @type {Array<GetSubAccountUniversalTransferV1RespResultInner>}
     * @memberof GetSubAccountUniversalTransferV1Resp
     */
    'result'?: Array<GetSubAccountUniversalTransferV1RespResultInner>;
    /**
     * 
     * @type {number}
     * @memberof GetSubAccountUniversalTransferV1Resp
     */
    'totalCount'?: number;
}

