/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetMiningPubAlgoListV1RespDataInner
 */
export interface GetMiningPubAlgoListV1RespDataInner {
    /**
     * 
     * @type {number}
     * @memberof GetMiningPubAlgoListV1RespDataInner
     */
    'algoId'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetMiningPubAlgoListV1RespDataInner
     */
    'algoName'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetMiningPubAlgoListV1RespDataInner
     */
    'poolIndex'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetMiningPubAlgoListV1RespDataInner
     */
    'unit'?: string;
}

