/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetLoanFlexibleLiquidationHistoryV2RespRowsInner } from './get-loan-flexible-liquidation-history-v2-resp-rows-inner';

/**
 * 
 * @export
 * @interface GetLoanFlexibleLiquidationHistoryV2Resp
 */
export interface GetLoanFlexibleLiquidationHistoryV2Resp {
    /**
     * 
     * @type {Array<GetLoanFlexibleLiquidationHistoryV2RespRowsInner>}
     * @memberof GetLoanFlexibleLiquidationHistoryV2Resp
     */
    'rows'?: Array<GetLoanFlexibleLiquidationHistoryV2RespRowsInner>;
    /**
     * 
     * @type {number}
     * @memberof GetLoanFlexibleLiquidationHistoryV2Resp
     */
    'total'?: number;
}

