/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetFiatOrdersV1RespDataInner
 */
export interface GetFiatOrdersV1RespDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetFiatOrdersV1RespDataInner
     */
    'amount'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetFiatOrdersV1RespDataInner
     */
    'createTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetFiatOrdersV1RespDataInner
     */
    'fiatCurrency'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFiatOrdersV1RespDataInner
     */
    'indicatedAmount'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFiatOrdersV1RespDataInner
     */
    'method'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFiatOrdersV1RespDataInner
     */
    'orderNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFiatOrdersV1RespDataInner
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFiatOrdersV1RespDataInner
     */
    'totalFee'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetFiatOrdersV1RespDataInner
     */
    'updateTime'?: number;
}

