/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetAccountCommissionV3RespDiscount
 */
export interface GetAccountCommissionV3RespDiscount {
    /**
     * 
     * @type {string}
     * @memberof GetAccountCommissionV3RespDiscount
     */
    'discount'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountCommissionV3RespDiscount
     */
    'discountAsset'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetAccountCommissionV3RespDiscount
     */
    'enabledForAccount'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetAccountCommissionV3RespDiscount
     */
    'enabledForSymbol'?: boolean;
}

