/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetAlgoFuturesSubOrdersV1RespSubOrdersInner
 */
export interface GetAlgoFuturesSubOrdersV1RespSubOrdersInner {
    /**
     * 
     * @type {number}
     * @memberof GetAlgoFuturesSubOrdersV1RespSubOrdersInner
     */
    'algoId'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAlgoFuturesSubOrdersV1RespSubOrdersInner
     */
    'avgPrice'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetAlgoFuturesSubOrdersV1RespSubOrdersInner
     */
    'bookTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAlgoFuturesSubOrdersV1RespSubOrdersInner
     */
    'executedAmt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAlgoFuturesSubOrdersV1RespSubOrdersInner
     */
    'executedQty'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAlgoFuturesSubOrdersV1RespSubOrdersInner
     */
    'feeAmt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAlgoFuturesSubOrdersV1RespSubOrdersInner
     */
    'feeAsset'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetAlgoFuturesSubOrdersV1RespSubOrdersInner
     */
    'orderId'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAlgoFuturesSubOrdersV1RespSubOrdersInner
     */
    'orderStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAlgoFuturesSubOrdersV1RespSubOrdersInner
     */
    'origQty'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAlgoFuturesSubOrdersV1RespSubOrdersInner
     */
    'side'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetAlgoFuturesSubOrdersV1RespSubOrdersInner
     */
    'subId'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAlgoFuturesSubOrdersV1RespSubOrdersInner
     */
    'symbol'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAlgoFuturesSubOrdersV1RespSubOrdersInner
     */
    'timeInForce'?: string;
}

