/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetMiningHashTransferConfigDetailsListV1RespData } from './get-mining-hash-transfer-config-details-list-v1-resp-data';

/**
 * 
 * @export
 * @interface GetMiningHashTransferConfigDetailsListV1Resp
 */
export interface GetMiningHashTransferConfigDetailsListV1Resp {
    /**
     * 
     * @type {number}
     * @memberof GetMiningHashTransferConfigDetailsListV1Resp
     */
    'code'?: number;
    /**
     * 
     * @type {GetMiningHashTransferConfigDetailsListV1RespData}
     * @memberof GetMiningHashTransferConfigDetailsListV1Resp
     */
    'data'?: GetMiningHashTransferConfigDetailsListV1RespData;
    /**
     * 
     * @type {string}
     * @memberof GetMiningHashTransferConfigDetailsListV1Resp
     */
    'msg'?: string;
}

