/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetSubAccountFuturesAccountV1RespAssetsInner
 */
export interface GetSubAccountFuturesAccountV1RespAssetsInner {
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesAccountV1RespAssetsInner
     */
    'asset'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesAccountV1RespAssetsInner
     */
    'initialMargin'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesAccountV1RespAssetsInner
     */
    'maintenanceMargin'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesAccountV1RespAssetsInner
     */
    'marginBalance'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesAccountV1RespAssetsInner
     */
    'maxWithdrawAmount'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesAccountV1RespAssetsInner
     */
    'openOrderInitialMargin'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesAccountV1RespAssetsInner
     */
    'positionInitialMargin'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesAccountV1RespAssetsInner
     */
    'unrealizedProfit'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountFuturesAccountV1RespAssetsInner
     */
    'walletBalance'?: string;
}

