/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetNftHistoryDepositV1RespListInner
 */
export interface GetNftHistoryDepositV1RespListInner {
    /**
     * 
     * @type {string}
     * @memberof GetNftHistoryDepositV1RespListInner
     */
    'contractAdrress'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetNftHistoryDepositV1RespListInner
     */
    'network'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetNftHistoryDepositV1RespListInner
     */
    'timestamp'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetNftHistoryDepositV1RespListInner
     */
    'tokenId'?: string;
    /**
     * 
     * @type {object}
     * @memberof GetNftHistoryDepositV1RespListInner
     */
    'txID'?: object | null;
}

