/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetMiningHashTransferConfigDetailsListV1RespDataConfigDetailsInner } from './get-mining-hash-transfer-config-details-list-v1-resp-data-config-details-inner';

/**
 * 
 * @export
 * @interface GetMiningHashTransferConfigDetailsListV1RespData
 */
export interface GetMiningHashTransferConfigDetailsListV1RespData {
    /**
     * 
     * @type {Array<GetMiningHashTransferConfigDetailsListV1RespDataConfigDetailsInner>}
     * @memberof GetMiningHashTransferConfigDetailsListV1RespData
     */
    'configDetails'?: Array<GetMiningHashTransferConfigDetailsListV1RespDataConfigDetailsInner>;
    /**
     * 
     * @type {number}
     * @memberof GetMiningHashTransferConfigDetailsListV1RespData
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetMiningHashTransferConfigDetailsListV1RespData
     */
    'totalNum'?: number;
}

