/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetMarginMaxBorrowableV1Resp
 */
export interface GetMarginMaxBorrowableV1Resp {
    /**
     * 
     * @type {string}
     * @memberof GetMarginMaxBorrowableV1Resp
     */
    'amount'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMarginMaxBorrowableV1Resp
     */
    'borrowLimit'?: string;
}

