/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetGiftcardCryptographyRsaPublicKeyV1Resp
 */
export interface GetGiftcardCryptographyRsaPublicKeyV1Resp {
    /**
     * 
     * @type {string}
     * @memberof GetGiftcardCryptographyRsaPublicKeyV1Resp
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetGiftcardCryptographyRsaPublicKeyV1Resp
     */
    'data'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetGiftcardCryptographyRsaPublicKeyV1Resp
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetGiftcardCryptographyRsaPublicKeyV1Resp
     */
    'success'?: boolean;
}

