/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetBrokerUniversalTransferV1RespItem
 */
export interface GetBrokerUniversalTransferV1RespItem {
    /**
     * 
     * @type {string}
     * @memberof GetBrokerUniversalTransferV1RespItem
     */
    'asset'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetBrokerUniversalTransferV1RespItem
     */
    'clientTranId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetBrokerUniversalTransferV1RespItem
     */
    'fromAccountType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetBrokerUniversalTransferV1RespItem
     */
    'qty'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetBrokerUniversalTransferV1RespItem
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetBrokerUniversalTransferV1RespItem
     */
    'time'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetBrokerUniversalTransferV1RespItem
     */
    'toAccountType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetBrokerUniversalTransferV1RespItem
     */
    'toId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetBrokerUniversalTransferV1RespItem
     */
    'txnId'?: string;
}

