/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetDepthV3Resp
 */
export interface GetDepthV3Resp {
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof GetDepthV3Resp
     */
    'asks'?: Array<Array<string>>;
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof GetDepthV3Resp
     */
    'bids'?: Array<Array<string>>;
    /**
     * 
     * @type {number}
     * @memberof GetDepthV3Resp
     */
    'lastUpdateId'?: number;
}

