/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetSimpleEarnLockedListV1RespRowsInner } from './get-simple-earn-locked-list-v1-resp-rows-inner';

/**
 * 
 * @export
 * @interface GetSimpleEarnLockedListV1Resp
 */
export interface GetSimpleEarnLockedListV1Resp {
    /**
     * 
     * @type {Array<GetSimpleEarnLockedListV1RespRowsInner>}
     * @memberof GetSimpleEarnLockedListV1Resp
     */
    'rows'?: Array<GetSimpleEarnLockedListV1RespRowsInner>;
    /**
     * 
     * @type {number}
     * @memberof GetSimpleEarnLockedListV1Resp
     */
    'total'?: number;
}

