/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
 */
export interface GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner {
    /**
     * 
     * @type {string}
     * @memberof GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
     */
    'amount'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
     */
    'asset'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
     */
    'deliverDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
     */
    'estExtraRewardAmt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
     */
    'extraRewardAsset'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
     */
    'isComplete'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
     */
    'lockPeriod'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
     */
    'lossAmount'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
     */
    'originalAmount'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
     */
    'positionId'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
     */
    'redeemId'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
     */
    'rewardAmt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
     */
    'rewardAsset'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
     */
    'time'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetSimpleEarnLockedHistoryRedemptionRecordV1RespRowsInner
     */
    'type'?: string;
}

