/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetSubAccountStatusV1RespItem
 */
export interface GetSubAccountStatusV1RespItem {
    /**
     * 
     * @type {string}
     * @memberof GetSubAccountStatusV1RespItem
     */
    'email'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetSubAccountStatusV1RespItem
     */
    'insertTime'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetSubAccountStatusV1RespItem
     */
    'isFutureEnabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetSubAccountStatusV1RespItem
     */
    'isMarginEnabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetSubAccountStatusV1RespItem
     */
    'isSubUserEnabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetSubAccountStatusV1RespItem
     */
    'isUserActive'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetSubAccountStatusV1RespItem
     */
    'mobile'?: number;
}

