/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetFuturesHistDataLinkV1RespDataInner } from './get-futures-hist-data-link-v1-resp-data-inner';

/**
 * 
 * @export
 * @interface GetFuturesHistDataLinkV1Resp
 */
export interface GetFuturesHistDataLinkV1Resp {
    /**
     * 
     * @type {Array<GetFuturesHistDataLinkV1RespDataInner>}
     * @memberof GetFuturesHistDataLinkV1Resp
     */
    'data'?: Array<GetFuturesHistDataLinkV1RespDataInner>;
}

