/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetMiningStatisticsUserStatusV1RespDataProfitToday } from './get-mining-statistics-user-status-v1-resp-data-profit-today';

/**
 * 
 * @export
 * @interface GetMiningStatisticsUserStatusV1RespData
 */
export interface GetMiningStatisticsUserStatusV1RespData {
    /**
     * 
     * @type {string}
     * @memberof GetMiningStatisticsUserStatusV1RespData
     */
    'algo'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMiningStatisticsUserStatusV1RespData
     */
    'dayHashRate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMiningStatisticsUserStatusV1RespData
     */
    'fifteenMinHashRate'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetMiningStatisticsUserStatusV1RespData
     */
    'invalidNum'?: number;
    /**
     * 
     * @type {GetMiningStatisticsUserStatusV1RespDataProfitToday}
     * @memberof GetMiningStatisticsUserStatusV1RespData
     */
    'profitToday'?: GetMiningStatisticsUserStatusV1RespDataProfitToday;
    /**
     * 
     * @type {GetMiningStatisticsUserStatusV1RespDataProfitToday}
     * @memberof GetMiningStatisticsUserStatusV1RespData
     */
    'profitYesterday'?: GetMiningStatisticsUserStatusV1RespDataProfitToday;
    /**
     * 
     * @type {string}
     * @memberof GetMiningStatisticsUserStatusV1RespData
     */
    'unit'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMiningStatisticsUserStatusV1RespData
     */
    'userName'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetMiningStatisticsUserStatusV1RespData
     */
    'validNum'?: number;
}

