/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetAssetTradeFeeV1RespItem
 */
export interface GetAssetTradeFeeV1RespItem {
    /**
     * 
     * @type {string}
     * @memberof GetAssetTradeFeeV1RespItem
     */
    'makerCommission'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAssetTradeFeeV1RespItem
     */
    'symbol'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAssetTradeFeeV1RespItem
     */
    'takerCommission'?: string;
}

