/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SpotCreateOrderCancelReplaceV3Data } from './spot-create-order-cancel-replace-v3-data';

/**
 * 
 * @export
 * @interface SpotCreateOrderCancelReplaceV3FailResp
 */
export interface SpotCreateOrderCancelReplaceV3FailResp {
    /**
     * 
     * @type {number}
     * @memberof SpotCreateOrderCancelReplaceV3FailResp
     */
    'code'?: number;
    /**
     * 
     * @type {SpotCreateOrderCancelReplaceV3Data}
     * @memberof SpotCreateOrderCancelReplaceV3FailResp
     */
    'data'?: SpotCreateOrderCancelReplaceV3Data;
    /**
     * 
     * @type {string}
     * @memberof SpotCreateOrderCancelReplaceV3FailResp
     */
    'msg'?: string;
}

