/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SpotGetTickerBookTickerV3RespItem } from './spot-get-ticker-book-ticker-v3-resp-item';

/**
 * @type SpotGetTickerBookTickerV3Resp
 * @export
 */
export type SpotGetTickerBookTickerV3Resp = Array<SpotGetTickerBookTickerV3RespItem> | SpotGetTickerBookTickerV3RespItem;


