/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SpotCreateOrderListOcoV3RespOrdersInner } from './spot-create-order-list-oco-v3-resp-orders-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { SpotCreateOrderOcoV3RespOrderReportsInner } from './spot-create-order-oco-v3-resp-order-reports-inner';

/**
 * 
 * @export
 * @interface SpotCreateOrderOcoV3Resp
 */
export interface SpotCreateOrderOcoV3Resp {
    /**
     * 
     * @type {string}
     * @memberof SpotCreateOrderOcoV3Resp
     */
    'contingencyType'?: string;
    /**
     * 
     * @type {string}
     * @memberof SpotCreateOrderOcoV3Resp
     */
    'listClientOrderId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SpotCreateOrderOcoV3Resp
     */
    'listOrderStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof SpotCreateOrderOcoV3Resp
     */
    'listStatusType'?: string;
    /**
     * 
     * @type {number}
     * @memberof SpotCreateOrderOcoV3Resp
     */
    'orderListId'?: number;
    /**
     * 
     * @type {Array<SpotCreateOrderOcoV3RespOrderReportsInner>}
     * @memberof SpotCreateOrderOcoV3Resp
     */
    'orderReports'?: Array<SpotCreateOrderOcoV3RespOrderReportsInner>;
    /**
     * 
     * @type {Array<SpotCreateOrderListOcoV3RespOrdersInner>}
     * @memberof SpotCreateOrderOcoV3Resp
     */
    'orders'?: Array<SpotCreateOrderListOcoV3RespOrdersInner>;
    /**
     * 
     * @type {string}
     * @memberof SpotCreateOrderOcoV3Resp
     */
    'symbol'?: string;
    /**
     * 
     * @type {number}
     * @memberof SpotCreateOrderOcoV3Resp
     */
    'transactionTime'?: number;
}

