/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SpotDeleteOpenOrdersV3RespOrderItem
 */
export interface SpotDeleteOpenOrdersV3RespOrderItem {
    /**
     * 
     * @type {string}
     * @memberof SpotDeleteOpenOrdersV3RespOrderItem
     */
    'clientOrderId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SpotDeleteOpenOrdersV3RespOrderItem
     */
    'cummulativeQuoteQty'?: string;
    /**
     * 
     * @type {string}
     * @memberof SpotDeleteOpenOrdersV3RespOrderItem
     */
    'executedQty'?: string;
    /**
     * 
     * @type {number}
     * @memberof SpotDeleteOpenOrdersV3RespOrderItem
     */
    'orderId'?: number;
    /**
     * 
     * @type {number}
     * @memberof SpotDeleteOpenOrdersV3RespOrderItem
     */
    'orderListId'?: number;
    /**
     * 
     * @type {string}
     * @memberof SpotDeleteOpenOrdersV3RespOrderItem
     */
    'origClientOrderId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SpotDeleteOpenOrdersV3RespOrderItem
     */
    'origQty'?: string;
    /**
     * 
     * @type {string}
     * @memberof SpotDeleteOpenOrdersV3RespOrderItem
     */
    'price'?: string;
    /**
     * 
     * @type {string}
     * @memberof SpotDeleteOpenOrdersV3RespOrderItem
     */
    'selfTradePreventionMode'?: string;
    /**
     * 
     * @type {string}
     * @memberof SpotDeleteOpenOrdersV3RespOrderItem
     */
    'side'?: string;
    /**
     * 
     * @type {string}
     * @memberof SpotDeleteOpenOrdersV3RespOrderItem
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof SpotDeleteOpenOrdersV3RespOrderItem
     */
    'symbol'?: string;
    /**
     * 
     * @type {string}
     * @memberof SpotDeleteOpenOrdersV3RespOrderItem
     */
    'timeInForce'?: string;
    /**
     * 
     * @type {number}
     * @memberof SpotDeleteOpenOrdersV3RespOrderItem
     */
    'transactTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof SpotDeleteOpenOrdersV3RespOrderItem
     */
    'type'?: string;
}

