/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { APIError } from './apierror';
// May contain unused imports in some cases
// @ts-ignore
import type { SpotCreateOrderCancelReplaceV3NewOrderResp } from './spot-create-order-cancel-replace-v3-new-order-resp';
// May contain unused imports in some cases
// @ts-ignore
import type { SpotCreateOrderCancelReplaceV3NewOrderRespFillsInner } from './spot-create-order-cancel-replace-v3-new-order-resp-fills-inner';

/**
 * @type SpotCreateOrderCancelReplaceV3DataNewOrderResponse
 * @export
 */
export type SpotCreateOrderCancelReplaceV3DataNewOrderResponse = APIError | SpotCreateOrderCancelReplaceV3NewOrderResp;


