/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SpotGetAccountCommissionV3RespStandardCommission } from './spot-get-account-commission-v3-resp-standard-commission';
// May contain unused imports in some cases
// @ts-ignore
import type { SpotGetAccountV3RespBalancesInner } from './spot-get-account-v3-resp-balances-inner';

/**
 * 
 * @export
 * @interface SpotGetAccountV3Resp
 */
export interface SpotGetAccountV3Resp {
    /**
     * 
     * @type {string}
     * @memberof SpotGetAccountV3Resp
     */
    'accountType'?: string;
    /**
     * 
     * @type {Array<SpotGetAccountV3RespBalancesInner>}
     * @memberof SpotGetAccountV3Resp
     */
    'balances'?: Array<SpotGetAccountV3RespBalancesInner>;
    /**
     * 
     * @type {boolean}
     * @memberof SpotGetAccountV3Resp
     */
    'brokered'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SpotGetAccountV3Resp
     */
    'buyerCommission'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SpotGetAccountV3Resp
     */
    'canDeposit'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SpotGetAccountV3Resp
     */
    'canTrade'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SpotGetAccountV3Resp
     */
    'canWithdraw'?: boolean;
    /**
     * 
     * @type {SpotGetAccountCommissionV3RespStandardCommission}
     * @memberof SpotGetAccountV3Resp
     */
    'commissionRates'?: SpotGetAccountCommissionV3RespStandardCommission;
    /**
     * 
     * @type {number}
     * @memberof SpotGetAccountV3Resp
     */
    'makerCommission'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof SpotGetAccountV3Resp
     */
    'permissions'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof SpotGetAccountV3Resp
     */
    'preventSor'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SpotGetAccountV3Resp
     */
    'requireSelfTradePrevention'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SpotGetAccountV3Resp
     */
    'sellerCommission'?: number;
    /**
     * 
     * @type {number}
     * @memberof SpotGetAccountV3Resp
     */
    'takerCommission'?: number;
    /**
     * 
     * @type {number}
     * @memberof SpotGetAccountV3Resp
     */
    'uid'?: number;
    /**
     * 
     * @type {number}
     * @memberof SpotGetAccountV3Resp
     */
    'updateTime'?: number;
}

