/* tslint:disable */
/* eslint-disable */
/**
 * Binance COIN-M Futures API
 * OpenAPI specification for Binance exchange - Cmfutures API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CmfuturesUpdateBatchOrdersV1RespItem
 */
export interface CmfuturesUpdateBatchOrdersV1RespItem {
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'avgPrice'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'clientOrderId'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'closePosition'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'cumBase'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'cumQty'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'executedQty'?: string;
    /**
     * 
     * @type {number}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'orderId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'origQty'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'origType'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'pair'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'positionSide'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'price'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'priceMatch'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'priceProtect'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'reduceOnly'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'selfTradePreventionMode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'side'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'stopPrice'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'symbol'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'timeInForce'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'type'?: string;
    /**
     * 
     * @type {number}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'updateTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesUpdateBatchOrdersV1RespItem
     */
    'workingType'?: string;
}

