/* tslint:disable */
/* eslint-disable */
/**
 * Binance COIN-M Futures API
 * OpenAPI specification for Binance exchange - Cmfutures API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetPositionMarginHistoryV1RespItem
 */
export interface GetPositionMarginHistoryV1RespItem {
    /**
     * 
     * @type {string}
     * @memberof GetPositionMarginHistoryV1RespItem
     */
    'amount'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionMarginHistoryV1RespItem
     */
    'asset'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionMarginHistoryV1RespItem
     */
    'positionSide'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPositionMarginHistoryV1RespItem
     */
    'symbol'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetPositionMarginHistoryV1RespItem
     */
    'time'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetPositionMarginHistoryV1RespItem
     */
    'type'?: number;
}

