/* tslint:disable */
/* eslint-disable */
/**
 * Binance COIN-M Futures API
 * OpenAPI specification for Binance exchange - Cmfutures API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetOrderAmendmentV1RespItemAmendmentOrigQty
 */
export interface GetOrderAmendmentV1RespItemAmendmentOrigQty {
    /**
     * 
     * @type {string}
     * @memberof GetOrderAmendmentV1RespItemAmendmentOrigQty
     */
    'after'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOrderAmendmentV1RespItemAmendmentOrigQty
     */
    'before'?: string;
}

