/* tslint:disable */
/* eslint-disable */
/**
 * Binance COIN-M Futures API
 * OpenAPI specification for Binance exchange - Cmfutures API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetPositionSideDualV1Resp
 */
export interface GetPositionSideDualV1Resp {
    /**
     * 
     * @type {boolean}
     * @memberof GetPositionSideDualV1Resp
     */
    'dualSidePosition'?: boolean;
}

