/* tslint:disable */
/* eslint-disable */
/**
 * Binance COIN-M Futures API
 * OpenAPI specification for Binance exchange - Cmfutures API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetPmAccountInfoV1Resp
 */
export interface GetPmAccountInfoV1Resp {
    /**
     * 
     * @type {string}
     * @memberof GetPmAccountInfoV1Resp
     */
    'asset'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPmAccountInfoV1Resp
     */
    'maxWithdrawAmount'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPmAccountInfoV1Resp
     */
    'maxWithdrawAmountUSD'?: string;
}

