/* tslint:disable */
/* eslint-disable */
/**
 * Binance COIN-M Futures API
 * OpenAPI specification for Binance exchange - Cmfutures API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetFuturesDataTakerBuySellVolRespItem
 */
export interface GetFuturesDataTakerBuySellVolRespItem {
    /**
     * 
     * @type {string}
     * @memberof GetFuturesDataTakerBuySellVolRespItem
     */
    'contractType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFuturesDataTakerBuySellVolRespItem
     */
    'pair'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFuturesDataTakerBuySellVolRespItem
     */
    'takerBuyVol'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFuturesDataTakerBuySellVolRespItem
     */
    'takerBuyVolValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFuturesDataTakerBuySellVolRespItem
     */
    'takerSellVol'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFuturesDataTakerBuySellVolRespItem
     */
    'takerSellVolValue'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetFuturesDataTakerBuySellVolRespItem
     */
    'timestamp'?: number;
}

