/* tslint:disable */
/* eslint-disable */
/**
 * Binance Margin Trading API
 * OpenAPI specification for Binance exchange - Margin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MarginGetMarginAccountV1RespUserAssetsInner } from './margin-get-margin-account-v1-resp-user-assets-inner';

/**
 * 
 * @export
 * @interface MarginGetMarginAccountV1Resp
 */
export interface MarginGetMarginAccountV1Resp {
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginAccountV1Resp
     */
    'TotalCollateralValueInUSDT'?: string;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginAccountV1Resp
     */
    'accountType'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MarginGetMarginAccountV1Resp
     */
    'borrowEnabled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginAccountV1Resp
     */
    'collateralMarginLevel'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MarginGetMarginAccountV1Resp
     */
    'created'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginAccountV1Resp
     */
    'marginLevel'?: string;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginAccountV1Resp
     */
    'totalAssetOfBtc'?: string;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginAccountV1Resp
     */
    'totalLiabilityOfBtc'?: string;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginAccountV1Resp
     */
    'totalNetAssetOfBtc'?: string;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginAccountV1Resp
     */
    'totalOpenOrderLossInUSDT'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MarginGetMarginAccountV1Resp
     */
    'tradeEnabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MarginGetMarginAccountV1Resp
     */
    'transferInEnabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MarginGetMarginAccountV1Resp
     */
    'transferOutEnabled'?: boolean;
    /**
     * 
     * @type {Array<MarginGetMarginAccountV1RespUserAssetsInner>}
     * @memberof MarginGetMarginAccountV1Resp
     */
    'userAssets'?: Array<MarginGetMarginAccountV1RespUserAssetsInner>;
}

