/* tslint:disable */
/* eslint-disable */
/**
 * Binance Margin Trading API
 * OpenAPI specification for Binance exchange - Margin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MarginGetMarginPriceIndexV1Resp
 */
export interface MarginGetMarginPriceIndexV1Resp {
    /**
     * 
     * @type {number}
     * @memberof MarginGetMarginPriceIndexV1Resp
     */
    'calcTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginPriceIndexV1Resp
     */
    'price'?: string;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginPriceIndexV1Resp
     */
    'symbol'?: string;
}

