/* tslint:disable */
/* eslint-disable */
/**
 * Binance Margin Trading API
 * OpenAPI specification for Binance exchange - Margin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MarginGetMarginDelistScheduleV1RespItem
 */
export interface MarginGetMarginDelistScheduleV1RespItem {
    /**
     * 
     * @type {Array<string>}
     * @memberof MarginGetMarginDelistScheduleV1RespItem
     */
    'crossMarginAssets'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof MarginGetMarginDelistScheduleV1RespItem
     */
    'delistTime'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof MarginGetMarginDelistScheduleV1RespItem
     */
    'isolatedMarginSymbols'?: Array<string>;
}

