/* tslint:disable */
/* eslint-disable */
/**
 * Binance Margin Trading API
 * OpenAPI specification for Binance exchange - Margin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MarginGetMarginCapitalFlowV1RespItem
 */
export interface MarginGetMarginCapitalFlowV1RespItem {
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginCapitalFlowV1RespItem
     */
    'amount'?: string;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginCapitalFlowV1RespItem
     */
    'asset'?: string;
    /**
     * 
     * @type {number}
     * @memberof MarginGetMarginCapitalFlowV1RespItem
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginCapitalFlowV1RespItem
     */
    'symbol'?: string;
    /**
     * 
     * @type {number}
     * @memberof MarginGetMarginCapitalFlowV1RespItem
     */
    'timestamp'?: number;
    /**
     * 
     * @type {number}
     * @memberof MarginGetMarginCapitalFlowV1RespItem
     */
    'tranId'?: number;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginCapitalFlowV1RespItem
     */
    'type'?: string;
}

