/* tslint:disable */
/* eslint-disable */
/**
 * Binance Margin Trading API
 * OpenAPI specification for Binance exchange - Margin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MarginGetMarginNextHourlyInterestRateV1RespItem
 */
export interface MarginGetMarginNextHourlyInterestRateV1RespItem {
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginNextHourlyInterestRateV1RespItem
     */
    'asset'?: string;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginNextHourlyInterestRateV1RespItem
     */
    'nextHourlyInterestRate'?: string;
}

