/* tslint:disable */
/* eslint-disable */
/**
 * Binance Margin Trading API
 * OpenAPI specification for Binance exchange - Margin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MarginGetMarginApiKeyV1Resp
 */
export interface MarginGetMarginApiKeyV1Resp {
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginApiKeyV1Resp
     */
    'apiKey'?: string;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginApiKeyV1Resp
     */
    'apiName'?: string;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginApiKeyV1Resp
     */
    'ip'?: string;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginApiKeyV1Resp
     */
    'permissionMode'?: string;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginApiKeyV1Resp
     */
    'type'?: string;
}

