/* tslint:disable */
/* eslint-disable */
/**
 * Binance Margin Trading API
 * OpenAPI specification for Binance exchange - Margin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MarginGetMarginMyTradesV1RespItem
 */
export interface MarginGetMarginMyTradesV1RespItem {
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginMyTradesV1RespItem
     */
    'commission'?: string;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginMyTradesV1RespItem
     */
    'commissionAsset'?: string;
    /**
     * 
     * @type {number}
     * @memberof MarginGetMarginMyTradesV1RespItem
     */
    'id'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MarginGetMarginMyTradesV1RespItem
     */
    'isBestMatch'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MarginGetMarginMyTradesV1RespItem
     */
    'isBuyer'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MarginGetMarginMyTradesV1RespItem
     */
    'isIsolated'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MarginGetMarginMyTradesV1RespItem
     */
    'isMaker'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MarginGetMarginMyTradesV1RespItem
     */
    'orderId'?: number;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginMyTradesV1RespItem
     */
    'price'?: string;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginMyTradesV1RespItem
     */
    'qty'?: string;
    /**
     * 
     * @type {string}
     * @memberof MarginGetMarginMyTradesV1RespItem
     */
    'symbol'?: string;
    /**
     * 
     * @type {number}
     * @memberof MarginGetMarginMyTradesV1RespItem
     */
    'time'?: number;
}

