/* tslint:disable */
/* eslint-disable */
/**
 * Binance Options API
 * OpenAPI specification for Binance exchange - Options API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetMarginAccountV1RespAssetInner
 */
export interface GetMarginAccountV1RespAssetInner {
    /**
     * 
     * @type {string}
     * @memberof GetMarginAccountV1RespAssetInner
     */
    'asset'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMarginAccountV1RespAssetInner
     */
    'available'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMarginAccountV1RespAssetInner
     */
    'equity'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMarginAccountV1RespAssetInner
     */
    'initialMargin'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMarginAccountV1RespAssetInner
     */
    'lpProfit'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMarginAccountV1RespAssetInner
     */
    'maintMargin'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMarginAccountV1RespAssetInner
     */
    'marginBalance'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMarginAccountV1RespAssetInner
     */
    'unrealizedPNL'?: string;
}

