/* tslint:disable */
/* eslint-disable */
/**
 * Binance Options API
 * OpenAPI specification for Binance exchange - Options API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetAccountV1RespGreekInner
 */
export interface GetAccountV1RespGreekInner {
    /**
     * 
     * @type {string}
     * @memberof GetAccountV1RespGreekInner
     */
    'delta'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountV1RespGreekInner
     */
    'gamma'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountV1RespGreekInner
     */
    'theta'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountV1RespGreekInner
     */
    'underlying'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountV1RespGreekInner
     */
    'vega'?: string;
}

