/* tslint:disable */
/* eslint-disable */
/**
 * Binance Options API
 * OpenAPI specification for Binance exchange - Options API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateBlockOrderExecuteV1RespLegsInner } from './create-block-order-execute-v1-resp-legs-inner';

/**
 * 
 * @export
 * @interface OptionsCreateBlockOrderCreateV1Resp
 */
export interface OptionsCreateBlockOrderCreateV1Resp {
    /**
     * 
     * @type {string}
     * @memberof OptionsCreateBlockOrderCreateV1Resp
     */
    'blockTradeSettlementKey'?: string;
    /**
     * 
     * @type {number}
     * @memberof OptionsCreateBlockOrderCreateV1Resp
     */
    'expireTime'?: number;
    /**
     * 
     * @type {Array<CreateBlockOrderExecuteV1RespLegsInner>}
     * @memberof OptionsCreateBlockOrderCreateV1Resp
     */
    'legs'?: Array<CreateBlockOrderExecuteV1RespLegsInner>;
    /**
     * 
     * @type {string}
     * @memberof OptionsCreateBlockOrderCreateV1Resp
     */
    'liquidity'?: string;
    /**
     * 
     * @type {string}
     * @memberof OptionsCreateBlockOrderCreateV1Resp
     */
    'status'?: string;
}

