/* tslint:disable */
/* eslint-disable */
/**
 * Binance Portfolio Margin API
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateUmPositionSideDualV1Resp
 */
export interface CreateUmPositionSideDualV1Resp {
    /**
     * 
     * @type {number}
     * @memberof CreateUmPositionSideDualV1Resp
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateUmPositionSideDualV1Resp
     */
    'msg'?: string;
}

