/* tslint:disable */
/* eslint-disable */
/**
 * Binance Portfolio Margin API
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateUmOrderV1Resp
 */
export interface CreateUmOrderV1Resp {
    /**
     * 
     * @type {string}
     * @memberof CreateUmOrderV1Resp
     */
    'avgPrice'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUmOrderV1Resp
     */
    'clientOrderId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUmOrderV1Resp
     */
    'cumQty'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUmOrderV1Resp
     */
    'cumQuote'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUmOrderV1Resp
     */
    'executedQty'?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateUmOrderV1Resp
     */
    'goodTillDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateUmOrderV1Resp
     */
    'orderId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateUmOrderV1Resp
     */
    'origQty'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUmOrderV1Resp
     */
    'positionSide'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUmOrderV1Resp
     */
    'price'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUmOrderV1Resp
     */
    'priceMatch'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateUmOrderV1Resp
     */
    'reduceOnly'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateUmOrderV1Resp
     */
    'selfTradePreventionMode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUmOrderV1Resp
     */
    'side'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUmOrderV1Resp
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUmOrderV1Resp
     */
    'symbol'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUmOrderV1Resp
     */
    'timeInForce'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUmOrderV1Resp
     */
    'type'?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateUmOrderV1Resp
     */
    'updateTime'?: number;
}

