/* tslint:disable */
/* eslint-disable */
/**
 * Binance Portfolio Margin API
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetMarginMarginInterestHistoryV1RespRowsInner
 */
export interface GetMarginMarginInterestHistoryV1RespRowsInner {
    /**
     * 
     * @type {string}
     * @memberof GetMarginMarginInterestHistoryV1RespRowsInner
     */
    'asset'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMarginMarginInterestHistoryV1RespRowsInner
     */
    'interest'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetMarginMarginInterestHistoryV1RespRowsInner
     */
    'interestAccuredTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetMarginMarginInterestHistoryV1RespRowsInner
     */
    'interestRate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMarginMarginInterestHistoryV1RespRowsInner
     */
    'principal'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMarginMarginInterestHistoryV1RespRowsInner
     */
    'rawAsset'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetMarginMarginInterestHistoryV1RespRowsInner
     */
    'txId'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetMarginMarginInterestHistoryV1RespRowsInner
     */
    'type'?: string;
}

