/* tslint:disable */
/* eslint-disable */
/**
 * Binance Portfolio Margin API
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetUmApiTradingStatusV1RespIndicatorsBTCUSDTInner
 */
export interface GetUmApiTradingStatusV1RespIndicatorsBTCUSDTInner {
    /**
     * 
     * @type {string}
     * @memberof GetUmApiTradingStatusV1RespIndicatorsBTCUSDTInner
     */
    'indicator'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetUmApiTradingStatusV1RespIndicatorsBTCUSDTInner
     */
    'isLocked'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetUmApiTradingStatusV1RespIndicatorsBTCUSDTInner
     */
    'plannedRecoverTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUmApiTradingStatusV1RespIndicatorsBTCUSDTInner
     */
    'triggerValue'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUmApiTradingStatusV1RespIndicatorsBTCUSDTInner
     */
    'value'?: number;
}

