/* tslint:disable */
/* eslint-disable */
/**
 * Binance Portfolio Margin API
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetUmAccountConfigV1Resp
 */
export interface GetUmAccountConfigV1Resp {
    /**
     * 
     * @type {boolean}
     * @memberof GetUmAccountConfigV1Resp
     */
    'canDeposit'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetUmAccountConfigV1Resp
     */
    'canTrade'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetUmAccountConfigV1Resp
     */
    'canWithdraw'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetUmAccountConfigV1Resp
     */
    'dualSidePosition'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetUmAccountConfigV1Resp
     */
    'feeTier'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetUmAccountConfigV1Resp
     */
    'multiAssetsMargin'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetUmAccountConfigV1Resp
     */
    'tradeGroupId'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUmAccountConfigV1Resp
     */
    'updateTime'?: number;
}

