/* tslint:disable */
/* eslint-disable */
/**
 * Binance USD-M Futures API
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UmfuturesGetAccountV2RespAssetsInner } from './umfutures-get-account-v2-resp-assets-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { UmfuturesGetAccountV2RespPositionsInner } from './umfutures-get-account-v2-resp-positions-inner';

/**
 * 
 * @export
 * @interface UmfuturesGetAccountV2Resp
 */
export interface UmfuturesGetAccountV2Resp {
    /**
     * 
     * @type {Array<UmfuturesGetAccountV2RespAssetsInner>}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'assets'?: Array<UmfuturesGetAccountV2RespAssetsInner>;
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'availableBalance'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'canDeposit'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'canWithdraw'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'feeBurn'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'feeTier'?: number;
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'maxWithdrawAmount'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'multiAssetsMargin'?: boolean;
    /**
     * 
     * @type {Array<UmfuturesGetAccountV2RespPositionsInner>}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'positions'?: Array<UmfuturesGetAccountV2RespPositionsInner>;
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'totalCrossUnPnl'?: string;
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'totalCrossWalletBalance'?: string;
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'totalInitialMargin'?: string;
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'totalMaintMargin'?: string;
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'totalMarginBalance'?: string;
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'totalOpenOrderInitialMargin'?: string;
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'totalPositionInitialMargin'?: string;
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'totalUnrealizedProfit'?: string;
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'totalWalletBalance'?: string;
    /**
     * 
     * @type {number}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'tradeGroupId'?: number;
    /**
     * 
     * @type {number}
     * @memberof UmfuturesGetAccountV2Resp
     */
    'updateTime'?: number;
}

