/* tslint:disable */
/* eslint-disable */
/**
 * Binance USD-M Futures API
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UmfuturesGetTradeAsynIdV1Resp
 */
export interface UmfuturesGetTradeAsynIdV1Resp {
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetTradeAsynIdV1Resp
     */
    'downloadId'?: string;
    /**
     * 
     * @type {number}
     * @memberof UmfuturesGetTradeAsynIdV1Resp
     */
    'expirationTimestamp'?: number;
    /**
     * 
     * @type {object}
     * @memberof UmfuturesGetTradeAsynIdV1Resp
     */
    'isExpired'?: object | null;
    /**
     * 
     * @type {boolean}
     * @memberof UmfuturesGetTradeAsynIdV1Resp
     */
    'notified'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetTradeAsynIdV1Resp
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof UmfuturesGetTradeAsynIdV1Resp
     */
    'url'?: string;
}

