/* tslint:disable */
/* eslint-disable */
/**
 * Binance COIN-M Futures API
 * OpenAPI specification for Binance exchange - Cmfutures API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CmfuturesGetConstituentsV1RespConstituentsInner } from './cmfutures-get-constituents-v1-resp-constituents-inner';

/**
 * 
 * @export
 * @interface CmfuturesGetConstituentsV1Resp
 */
export interface CmfuturesGetConstituentsV1Resp {
    /**
     * 
     * @type {Array<CmfuturesGetConstituentsV1RespConstituentsInner>}
     * @memberof CmfuturesGetConstituentsV1Resp
     */
    'constituents'?: Array<CmfuturesGetConstituentsV1RespConstituentsInner>;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetConstituentsV1Resp
     */
    'symbol'?: string;
    /**
     * 
     * @type {number}
     * @memberof CmfuturesGetConstituentsV1Resp
     */
    'time'?: number;
}

