/* tslint:disable */
/* eslint-disable */
/**
 * Binance COIN-M Futures API
 * OpenAPI specification for Binance exchange - Cmfutures API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CmfuturesGetConstituentsV1RespConstituentsInner
 */
export interface CmfuturesGetConstituentsV1RespConstituentsInner {
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetConstituentsV1RespConstituentsInner
     */
    'exchange'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetConstituentsV1RespConstituentsInner
     */
    'symbol'?: string;
}

