/* tslint:disable */
/* eslint-disable */
/**
 * Binance COIN-M Futures API
 * OpenAPI specification for Binance exchange - Cmfutures API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CmfuturesGetFuturesDataTopLongShortAccountRatioRespItem
 */
export interface CmfuturesGetFuturesDataTopLongShortAccountRatioRespItem {
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetFuturesDataTopLongShortAccountRatioRespItem
     */
    'longAccount'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetFuturesDataTopLongShortAccountRatioRespItem
     */
    'longShortRatio'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetFuturesDataTopLongShortAccountRatioRespItem
     */
    'pair'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetFuturesDataTopLongShortAccountRatioRespItem
     */
    'shortAccount'?: string;
    /**
     * 
     * @type {number}
     * @memberof CmfuturesGetFuturesDataTopLongShortAccountRatioRespItem
     */
    'timestamp'?: number;
}

