/* tslint:disable */
/* eslint-disable */
/**
 * Binance COIN-M Futures API
 * OpenAPI specification for Binance exchange - Cmfutures API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CmfuturesGetOrderAmendmentV1RespItemAmendment } from './cmfutures-get-order-amendment-v1-resp-item-amendment';

/**
 * 
 * @export
 * @interface CmfuturesGetOrderAmendmentV1RespItem
 */
export interface CmfuturesGetOrderAmendmentV1RespItem {
    /**
     * 
     * @type {CmfuturesGetOrderAmendmentV1RespItemAmendment}
     * @memberof CmfuturesGetOrderAmendmentV1RespItem
     */
    'amendment'?: CmfuturesGetOrderAmendmentV1RespItemAmendment;
    /**
     * 
     * @type {number}
     * @memberof CmfuturesGetOrderAmendmentV1RespItem
     */
    'amendmentId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetOrderAmendmentV1RespItem
     */
    'clientOrderId'?: string;
    /**
     * 
     * @type {number}
     * @memberof CmfuturesGetOrderAmendmentV1RespItem
     */
    'orderId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetOrderAmendmentV1RespItem
     */
    'pair'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetOrderAmendmentV1RespItem
     */
    'symbol'?: string;
    /**
     * 
     * @type {number}
     * @memberof CmfuturesGetOrderAmendmentV1RespItem
     */
    'time'?: number;
}

