/* tslint:disable */
/* eslint-disable */
/**
 * Binance COIN-M Futures API
 * OpenAPI specification for Binance exchange - Cmfutures API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CmfuturesGetUserTradesV1RespItem
 */
export interface CmfuturesGetUserTradesV1RespItem {
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetUserTradesV1RespItem
     */
    'baseQty'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CmfuturesGetUserTradesV1RespItem
     */
    'buyer'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetUserTradesV1RespItem
     */
    'commission'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetUserTradesV1RespItem
     */
    'commissionAsset'?: string;
    /**
     * 
     * @type {number}
     * @memberof CmfuturesGetUserTradesV1RespItem
     */
    'id'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CmfuturesGetUserTradesV1RespItem
     */
    'maker'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetUserTradesV1RespItem
     */
    'marginAsset'?: string;
    /**
     * 
     * @type {number}
     * @memberof CmfuturesGetUserTradesV1RespItem
     */
    'orderId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetUserTradesV1RespItem
     */
    'pair'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetUserTradesV1RespItem
     */
    'positionSide'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetUserTradesV1RespItem
     */
    'price'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetUserTradesV1RespItem
     */
    'qty'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetUserTradesV1RespItem
     */
    'realizedPnl'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetUserTradesV1RespItem
     */
    'side'?: string;
    /**
     * 
     * @type {string}
     * @memberof CmfuturesGetUserTradesV1RespItem
     */
    'symbol'?: string;
    /**
     * 
     * @type {number}
     * @memberof CmfuturesGetUserTradesV1RespItem
     */
    'time'?: number;
}

