/* tslint:disable */
/* eslint-disable */
/**
 * Binance Spot API
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setBinanceAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIError } from '../model';
// @ts-ignore
import type { GetRebateTaxQueryV1Resp } from '../model';
/**
 * RebateApi - axios parameter creator
 * @export
 */
export const RebateApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get Spot Rebate History Records
         * @summary Get Spot Rebate History Records (USER_DATA)
         * @param {number} timestamp 
         * @param {number} [startTime] 
         * @param {number} [endTime] 
         * @param {number} [page] Default 1
         * @param {number} [recvWindow] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRebateTaxQueryV1: async (timestamp: number, startTime?: number, endTime?: number, page?: number, recvWindow?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'timestamp' is not null or undefined
            assertParamExists('getRebateTaxQueryV1', 'timestamp', timestamp)
            const localVarPath = `/sapi/v1/rebate/taxQuery`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required

            if (startTime !== undefined) {
                localVarQueryParameter['startTime'] = startTime;
            }

            if (endTime !== undefined) {
                localVarQueryParameter['endTime'] = endTime;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (recvWindow !== undefined) {
                localVarQueryParameter['recvWindow'] = recvWindow;
            }

            if (timestamp !== undefined) {
                localVarQueryParameter['timestamp'] = timestamp;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            // Handle Binance authentication with API key in header and signature in query parameters
            await setBinanceAuthToObject(localVarUrlObj, localVarRequestOptions, configuration);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RebateApi - functional programming interface
 * @export
 */
export const RebateApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RebateApiAxiosParamCreator(configuration)
    return {
        /**
         * Get Spot Rebate History Records
         * @summary Get Spot Rebate History Records (USER_DATA)
         * @param {number} timestamp 
         * @param {number} [startTime] 
         * @param {number} [endTime] 
         * @param {number} [page] Default 1
         * @param {number} [recvWindow] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRebateTaxQueryV1(timestamp: number, startTime?: number, endTime?: number, page?: number, recvWindow?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetRebateTaxQueryV1Resp>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRebateTaxQueryV1(timestamp, startTime, endTime, page, recvWindow, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RebateApi.getRebateTaxQueryV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RebateApi - factory interface
 * @export
 */
export const RebateApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RebateApiFp(configuration)
    return {
        /**
         * Get Spot Rebate History Records
         * @summary Get Spot Rebate History Records (USER_DATA)
         * @param {RebateApiGetRebateTaxQueryV1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRebateTaxQueryV1(requestParameters: RebateApiGetRebateTaxQueryV1Request, options?: RawAxiosRequestConfig): AxiosPromise<GetRebateTaxQueryV1Resp> {
            return localVarFp.getRebateTaxQueryV1(requestParameters.timestamp, requestParameters.startTime, requestParameters.endTime, requestParameters.page, requestParameters.recvWindow, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RebateApi - interface
 * @export
 * @interface RebateApi
 */
export interface RebateApiInterface {
    /**
     * Get Spot Rebate History Records
     * @summary Get Spot Rebate History Records (USER_DATA)
     * @param {RebateApiGetRebateTaxQueryV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RebateApiInterface
     */
    getRebateTaxQueryV1(requestParameters: RebateApiGetRebateTaxQueryV1Request, options?: RawAxiosRequestConfig): AxiosPromise<GetRebateTaxQueryV1Resp>;

}

/**
 * Request parameters for getRebateTaxQueryV1 operation in RebateApi.
 * @export
 * @interface RebateApiGetRebateTaxQueryV1Request
 */
export interface RebateApiGetRebateTaxQueryV1Request {
    /**
     * 
     * @type {number}
     * @memberof RebateApiGetRebateTaxQueryV1
     */
    readonly timestamp: number

    /**
     * 
     * @type {number}
     * @memberof RebateApiGetRebateTaxQueryV1
     */
    readonly startTime?: number

    /**
     * 
     * @type {number}
     * @memberof RebateApiGetRebateTaxQueryV1
     */
    readonly endTime?: number

    /**
     * Default 1
     * @type {number}
     * @memberof RebateApiGetRebateTaxQueryV1
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof RebateApiGetRebateTaxQueryV1
     */
    readonly recvWindow?: number
}

/**
 * RebateApi - object-oriented interface
 * @export
 * @class RebateApi
 * @extends {BaseAPI}
 */
export class RebateApi extends BaseAPI implements RebateApiInterface {
    /**
     * Get Spot Rebate History Records
     * @summary Get Spot Rebate History Records (USER_DATA)
     * @param {RebateApiGetRebateTaxQueryV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RebateApi
     */
    public getRebateTaxQueryV1(requestParameters: RebateApiGetRebateTaxQueryV1Request, options?: RawAxiosRequestConfig) {
        return RebateApiFp(this.configuration).getRebateTaxQueryV1(requestParameters.timestamp, requestParameters.startTime, requestParameters.endTime, requestParameters.page, requestParameters.recvWindow, options).then((request) => request(this.axios, this.basePath));
    }
}

