/* tslint:disable */
/* eslint-disable */
/**
 * Binance Convert API
 * OpenAPI specification for Binance exchange - Convert API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConvertCreateConvertLimitQueryOpenOrdersV1RespListInner } from './convert-create-convert-limit-query-open-orders-v1-resp-list-inner';

/**
 * 
 * @export
 * @interface ConvertCreateConvertLimitQueryOpenOrdersV1Resp
 */
export interface ConvertCreateConvertLimitQueryOpenOrdersV1Resp {
    /**
     * 
     * @type {Array<ConvertCreateConvertLimitQueryOpenOrdersV1RespListInner>}
     * @memberof ConvertCreateConvertLimitQueryOpenOrdersV1Resp
     */
    'list'?: Array<ConvertCreateConvertLimitQueryOpenOrdersV1RespListInner>;
}

