/* tslint:disable */
/* eslint-disable */
/**
 * Binance Options API
 * OpenAPI specification for Binance exchange - Options API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OptionsDeleteBatchOrdersV1RespItem
 */
export interface OptionsDeleteBatchOrdersV1RespItem {
    /**
     * 
     * @type {string}
     * @memberof OptionsDeleteBatchOrdersV1RespItem
     */
    'avgPrice'?: string;
    /**
     * 
     * @type {string}
     * @memberof OptionsDeleteBatchOrdersV1RespItem
     */
    'clientOrderId'?: string;
    /**
     * 
     * @type {number}
     * @memberof OptionsDeleteBatchOrdersV1RespItem
     */
    'createTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof OptionsDeleteBatchOrdersV1RespItem
     */
    'executedQty'?: string;
    /**
     * 
     * @type {number}
     * @memberof OptionsDeleteBatchOrdersV1RespItem
     */
    'fee'?: number;
    /**
     * 
     * @type {number}
     * @memberof OptionsDeleteBatchOrdersV1RespItem
     */
    'orderId'?: number;
    /**
     * 
     * @type {string}
     * @memberof OptionsDeleteBatchOrdersV1RespItem
     */
    'price'?: string;
    /**
     * 
     * @type {string}
     * @memberof OptionsDeleteBatchOrdersV1RespItem
     */
    'quantity'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDeleteBatchOrdersV1RespItem
     */
    'reduceOnly'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OptionsDeleteBatchOrdersV1RespItem
     */
    'side'?: string;
    /**
     * 
     * @type {string}
     * @memberof OptionsDeleteBatchOrdersV1RespItem
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof OptionsDeleteBatchOrdersV1RespItem
     */
    'symbol'?: string;
    /**
     * 
     * @type {string}
     * @memberof OptionsDeleteBatchOrdersV1RespItem
     */
    'timeInForce'?: string;
    /**
     * 
     * @type {string}
     * @memberof OptionsDeleteBatchOrdersV1RespItem
     */
    'type'?: string;
    /**
     * 
     * @type {number}
     * @memberof OptionsDeleteBatchOrdersV1RespItem
     */
    'updateTime'?: number;
}

