/* tslint:disable */
/* eslint-disable */
/**
 * Binance Options API
 * OpenAPI specification for Binance exchange - Options API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OptionsCreateMmpResetV1Resp
 */
export interface OptionsCreateMmpResetV1Resp {
    /**
     * 
     * @type {string}
     * @memberof OptionsCreateMmpResetV1Resp
     */
    'deltaLimit'?: string;
    /**
     * 
     * @type {number}
     * @memberof OptionsCreateMmpResetV1Resp
     */
    'frozenTimeInMilliseconds'?: number;
    /**
     * 
     * @type {number}
     * @memberof OptionsCreateMmpResetV1Resp
     */
    'lastTriggerTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof OptionsCreateMmpResetV1Resp
     */
    'qtyLimit'?: string;
    /**
     * 
     * @type {string}
     * @memberof OptionsCreateMmpResetV1Resp
     */
    'underlying'?: string;
    /**
     * 
     * @type {number}
     * @memberof OptionsCreateMmpResetV1Resp
     */
    'underlyingId'?: number;
    /**
     * 
     * @type {number}
     * @memberof OptionsCreateMmpResetV1Resp
     */
    'windowTimeInMilliseconds'?: number;
}

