/* tslint:disable */
/* eslint-disable */
/**
 * Binance Options API
 * OpenAPI specification for Binance exchange - Options API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OptionsGetOpenInterestV1RespItem
 */
export interface OptionsGetOpenInterestV1RespItem {
    /**
     * 
     * @type {string}
     * @memberof OptionsGetOpenInterestV1RespItem
     */
    'sumOpenInterest'?: string;
    /**
     * 
     * @type {string}
     * @memberof OptionsGetOpenInterestV1RespItem
     */
    'sumOpenInterestUsd'?: string;
    /**
     * 
     * @type {string}
     * @memberof OptionsGetOpenInterestV1RespItem
     */
    'symbol'?: string;
    /**
     * 
     * @type {string}
     * @memberof OptionsGetOpenInterestV1RespItem
     */
    'timestamp'?: string;
}

