/* tslint:disable */
/* eslint-disable */
/**
 * Binance Wallet API
 * OpenAPI specification for Binance exchange - Wallet API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WalletUpdateLocalentityDepositProvideInfoV1Resp
 */
export interface WalletUpdateLocalentityDepositProvideInfoV1Resp {
    /**
     * 
     * @type {boolean}
     * @memberof WalletUpdateLocalentityDepositProvideInfoV1Resp
     */
    'accepted'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WalletUpdateLocalentityDepositProvideInfoV1Resp
     */
    'info'?: string;
    /**
     * 
     * @type {number}
     * @memberof WalletUpdateLocalentityDepositProvideInfoV1Resp
     */
    'trId'?: number;
}

