/* tslint:disable */
/* eslint-disable */
/**
 * Binance Wallet API
 * OpenAPI specification for Binance exchange - Wallet API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WalletCreateAssetDustBtcV1RespDetailsInner } from './wallet-create-asset-dust-btc-v1-resp-details-inner';

/**
 * 
 * @export
 * @interface WalletCreateAssetDustBtcV1Resp
 */
export interface WalletCreateAssetDustBtcV1Resp {
    /**
     * 
     * @type {Array<WalletCreateAssetDustBtcV1RespDetailsInner>}
     * @memberof WalletCreateAssetDustBtcV1Resp
     */
    'details'?: Array<WalletCreateAssetDustBtcV1RespDetailsInner>;
    /**
     * 
     * @type {string}
     * @memberof WalletCreateAssetDustBtcV1Resp
     */
    'dribbletPercentage'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletCreateAssetDustBtcV1Resp
     */
    'totalTransferBNB'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletCreateAssetDustBtcV1Resp
     */
    'totalTransferBtc'?: string;
}

