/* tslint:disable */
/* eslint-disable */
/**
 * Binance Wallet API
 * OpenAPI specification for Binance exchange - Wallet API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WalletGetLocalentityWithdrawHistoryV2RespItem
 */
export interface WalletGetLocalentityWithdrawHistoryV2RespItem {
    /**
     * 
     * @type {string}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'addressTag'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'amount'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'applyTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'coin'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'completeTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'confirmNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'info'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'network'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'questionnaire'?: string;
    /**
     * 
     * @type {number}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'trId'?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'transactionFee'?: string;
    /**
     * 
     * @type {number}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'transferType'?: number;
    /**
     * 
     * @type {number}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'travelRuleStatus'?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'txId'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'txKey'?: string;
    /**
     * 
     * @type {number}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'walletType'?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'withdrawOrderId'?: string;
    /**
     * 
     * @type {number}
     * @memberof WalletGetLocalentityWithdrawHistoryV2RespItem
     */
    'withdrawalStatus'?: number;
}

