/* tslint:disable */
/* eslint-disable */
/**
 * Binance Wallet API
 * OpenAPI specification for Binance exchange - Wallet API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WalletGetAssetTransferV1RespRowsInner
 */
export interface WalletGetAssetTransferV1RespRowsInner {
    /**
     * 
     * @type {string}
     * @memberof WalletGetAssetTransferV1RespRowsInner
     */
    'amount'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletGetAssetTransferV1RespRowsInner
     */
    'asset'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletGetAssetTransferV1RespRowsInner
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof WalletGetAssetTransferV1RespRowsInner
     */
    'timestamp'?: number;
    /**
     * 
     * @type {number}
     * @memberof WalletGetAssetTransferV1RespRowsInner
     */
    'tranId'?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletGetAssetTransferV1RespRowsInner
     */
    'type'?: string;
}

