/* tslint:disable */
/* eslint-disable */
/**
 * Binance Wallet API
 * OpenAPI specification for Binance exchange - Wallet API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WalletGetAssetCustodyTransferHistoryV1RespRowsInner } from './wallet-get-asset-custody-transfer-history-v1-resp-rows-inner';

/**
 * 
 * @export
 * @interface WalletGetAssetCustodyTransferHistoryV1Resp
 */
export interface WalletGetAssetCustodyTransferHistoryV1Resp {
    /**
     * 
     * @type {Array<WalletGetAssetCustodyTransferHistoryV1RespRowsInner>}
     * @memberof WalletGetAssetCustodyTransferHistoryV1Resp
     */
    'rows'?: Array<WalletGetAssetCustodyTransferHistoryV1RespRowsInner>;
    /**
     * 
     * @type {number}
     * @memberof WalletGetAssetCustodyTransferHistoryV1Resp
     */
    'total'?: number;
}

