/* tslint:disable */
/* eslint-disable */
/**
 * Binance Portfolio Margin API
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PmarginGetCmIncomeV1RespItem
 */
export interface PmarginGetCmIncomeV1RespItem {
    /**
     * 
     * @type {string}
     * @memberof PmarginGetCmIncomeV1RespItem
     */
    'asset'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginGetCmIncomeV1RespItem
     */
    'income'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginGetCmIncomeV1RespItem
     */
    'incomeType'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginGetCmIncomeV1RespItem
     */
    'info'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginGetCmIncomeV1RespItem
     */
    'symbol'?: string;
    /**
     * 
     * @type {number}
     * @memberof PmarginGetCmIncomeV1RespItem
     */
    'time'?: number;
    /**
     * 
     * @type {string}
     * @memberof PmarginGetCmIncomeV1RespItem
     */
    'tradeId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginGetCmIncomeV1RespItem
     */
    'tranId'?: string;
}

