/* tslint:disable */
/* eslint-disable */
/**
 * Binance Portfolio Margin API
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PmarginGetPortfolioInterestHistoryV1RespItem
 */
export interface PmarginGetPortfolioInterestHistoryV1RespItem {
    /**
     * 
     * @type {string}
     * @memberof PmarginGetPortfolioInterestHistoryV1RespItem
     */
    'asset'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginGetPortfolioInterestHistoryV1RespItem
     */
    'interest'?: string;
    /**
     * 
     * @type {number}
     * @memberof PmarginGetPortfolioInterestHistoryV1RespItem
     */
    'interestAccuredTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof PmarginGetPortfolioInterestHistoryV1RespItem
     */
    'interestRate'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginGetPortfolioInterestHistoryV1RespItem
     */
    'principal'?: string;
}

