/* tslint:disable */
/* eslint-disable */
/**
 * Binance Portfolio Margin API
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PmarginDeleteMarginOrderListV1RespOrderReportsInner
 */
export interface PmarginDeleteMarginOrderListV1RespOrderReportsInner {
    /**
     * 
     * @type {string}
     * @memberof PmarginDeleteMarginOrderListV1RespOrderReportsInner
     */
    'clientOrderId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginDeleteMarginOrderListV1RespOrderReportsInner
     */
    'cummulativeQuoteQty'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginDeleteMarginOrderListV1RespOrderReportsInner
     */
    'executedQty'?: string;
    /**
     * 
     * @type {number}
     * @memberof PmarginDeleteMarginOrderListV1RespOrderReportsInner
     */
    'orderId'?: number;
    /**
     * 
     * @type {number}
     * @memberof PmarginDeleteMarginOrderListV1RespOrderReportsInner
     */
    'orderListId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PmarginDeleteMarginOrderListV1RespOrderReportsInner
     */
    'origClientOrderId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginDeleteMarginOrderListV1RespOrderReportsInner
     */
    'origQty'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginDeleteMarginOrderListV1RespOrderReportsInner
     */
    'price'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginDeleteMarginOrderListV1RespOrderReportsInner
     */
    'side'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginDeleteMarginOrderListV1RespOrderReportsInner
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginDeleteMarginOrderListV1RespOrderReportsInner
     */
    'stopPrice'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginDeleteMarginOrderListV1RespOrderReportsInner
     */
    'symbol'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginDeleteMarginOrderListV1RespOrderReportsInner
     */
    'timeInForce'?: string;
    /**
     * 
     * @type {string}
     * @memberof PmarginDeleteMarginOrderListV1RespOrderReportsInner
     */
    'type'?: string;
}

