/* tslint:disable */
/* eslint-disable */
/**
 * Binance Portfolio Margin API
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PmarginGetCmLeverageBracketV1RespItemBracketsInner } from './pmargin-get-cm-leverage-bracket-v1-resp-item-brackets-inner';

/**
 * 
 * @export
 * @interface PmarginGetCmLeverageBracketV1RespItem
 */
export interface PmarginGetCmLeverageBracketV1RespItem {
    /**
     * 
     * @type {Array<PmarginGetCmLeverageBracketV1RespItemBracketsInner>}
     * @memberof PmarginGetCmLeverageBracketV1RespItem
     */
    'brackets'?: Array<PmarginGetCmLeverageBracketV1RespItemBracketsInner>;
    /**
     * 
     * @type {string}
     * @memberof PmarginGetCmLeverageBracketV1RespItem
     */
    'symbol'?: string;
}

