/* tslint:disable */
/* eslint-disable */
/**
 * Binance Portfolio Margin Pro API
 * OpenAPI specification for Binance exchange - Pmarginpro API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PmarginproCreatePortfolioRedeemV1Resp
 */
export interface PmarginproCreatePortfolioRedeemV1Resp {
    /**
     * 
     * @type {string}
     * @memberof PmarginproCreatePortfolioRedeemV1Resp
     */
    'fromAsset'?: string;
    /**
     * 
     * @type {number}
     * @memberof PmarginproCreatePortfolioRedeemV1Resp
     */
    'fromAssetQty'?: number;
    /**
     * 
     * @type {number}
     * @memberof PmarginproCreatePortfolioRedeemV1Resp
     */
    'rate'?: number;
    /**
     * 
     * @type {string}
     * @memberof PmarginproCreatePortfolioRedeemV1Resp
     */
    'targetAsset'?: string;
    /**
     * 
     * @type {number}
     * @memberof PmarginproCreatePortfolioRedeemV1Resp
     */
    'targetAssetQty'?: number;
}

