/* tslint:disable */
/* eslint-disable */
/**
 * Binance Sub Account API
 * OpenAPI specification for Binance exchange - Subaccount API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SubaccountGetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerDataAssetsInner } from './subaccount-get-managed-subaccount-fetch-future-asset-v1-resp-snapshot-vos-inner-data-assets-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { SubaccountGetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerDataPositionInner } from './subaccount-get-managed-subaccount-fetch-future-asset-v1-resp-snapshot-vos-inner-data-position-inner';

/**
 * 
 * @export
 * @interface SubaccountGetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerData
 */
export interface SubaccountGetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerData {
    /**
     * 
     * @type {Array<SubaccountGetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerDataAssetsInner>}
     * @memberof SubaccountGetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerData
     */
    'assets'?: Array<SubaccountGetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerDataAssetsInner>;
    /**
     * 
     * @type {Array<SubaccountGetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerDataPositionInner>}
     * @memberof SubaccountGetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerData
     */
    'position'?: Array<SubaccountGetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerDataPositionInner>;
}

