/* tslint:disable */
/* eslint-disable */
/**
 * Binance Sub Account API
 * OpenAPI specification for Binance exchange - Subaccount API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SubaccountGetManagedSubaccountAccountSnapshotV1RespSnapshotVosInnerDataBalancesInner } from './subaccount-get-managed-subaccount-account-snapshot-v1-resp-snapshot-vos-inner-data-balances-inner';

/**
 * 
 * @export
 * @interface SubaccountGetManagedSubaccountAccountSnapshotV1RespSnapshotVosInnerData
 */
export interface SubaccountGetManagedSubaccountAccountSnapshotV1RespSnapshotVosInnerData {
    /**
     * 
     * @type {Array<SubaccountGetManagedSubaccountAccountSnapshotV1RespSnapshotVosInnerDataBalancesInner>}
     * @memberof SubaccountGetManagedSubaccountAccountSnapshotV1RespSnapshotVosInnerData
     */
    'balances'?: Array<SubaccountGetManagedSubaccountAccountSnapshotV1RespSnapshotVosInnerDataBalancesInner>;
    /**
     * 
     * @type {string}
     * @memberof SubaccountGetManagedSubaccountAccountSnapshotV1RespSnapshotVosInnerData
     */
    'totalAssetOfBtc'?: string;
}

