/* tslint:disable */
/* eslint-disable */
/**
 * Binance Sub Account API
 * OpenAPI specification for Binance exchange - Subaccount API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubaccountCreateSubAccountVirtualSubAccountV1Resp
 */
export interface SubaccountCreateSubAccountVirtualSubAccountV1Resp {
    /**
     * 
     * @type {string}
     * @memberof SubaccountCreateSubAccountVirtualSubAccountV1Resp
     */
    'email'?: string;
}

