/* tslint:disable */
/* eslint-disable */
/**
 * Binance Sub Account API
 * OpenAPI specification for Binance exchange - Subaccount API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SubaccountGetSubAccountMarginAccountSummaryV1RespSubAccountListInner } from './subaccount-get-sub-account-margin-account-summary-v1-resp-sub-account-list-inner';

/**
 * 
 * @export
 * @interface SubaccountGetSubAccountMarginAccountSummaryV1Resp
 */
export interface SubaccountGetSubAccountMarginAccountSummaryV1Resp {
    /**
     * 
     * @type {Array<SubaccountGetSubAccountMarginAccountSummaryV1RespSubAccountListInner>}
     * @memberof SubaccountGetSubAccountMarginAccountSummaryV1Resp
     */
    'subAccountList'?: Array<SubaccountGetSubAccountMarginAccountSummaryV1RespSubAccountListInner>;
    /**
     * 
     * @type {string}
     * @memberof SubaccountGetSubAccountMarginAccountSummaryV1Resp
     */
    'totalAssetOfBtc'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubaccountGetSubAccountMarginAccountSummaryV1Resp
     */
    'totalLiabilityOfBtc'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubaccountGetSubAccountMarginAccountSummaryV1Resp
     */
    'totalNetAssetOfBtc'?: string;
}

