/* tslint:disable */
/* eslint-disable */
/**
 * Binance Sub Account API
 * OpenAPI specification for Binance exchange - Subaccount API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner
 */
export interface SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner {
    /**
     * 
     * @type {string}
     * @memberof SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner
     */
    'bindParentEmail'?: string;
    /**
     * 
     * @type {number}
     * @memberof SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner
     */
    'bindParentUserId'?: number;
    /**
     * 
     * @type {string}
     * @memberof SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner
     */
    'email'?: string;
    /**
     * 
     * @type {number}
     * @memberof SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner
     */
    'insertTimeStamp'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner
     */
    'isFutureEnabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner
     */
    'isMarginEnabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner
     */
    'isSignedLVTRiskAgreement'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner
     */
    'isSubUserEnabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner
     */
    'isUserActive'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner
     */
    'managersubUserId'?: number;
    /**
     * 
     * @type {number}
     * @memberof SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner
     */
    'rootUserId'?: number;
}

