/* tslint:disable */
/* eslint-disable */
/**
 * Binance Sub Account API
 * OpenAPI specification for Binance exchange - Subaccount API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SubaccountGetSubAccountListV1RespSubAccountsInner } from './subaccount-get-sub-account-list-v1-resp-sub-accounts-inner';

/**
 * 
 * @export
 * @interface SubaccountGetSubAccountListV1Resp
 */
export interface SubaccountGetSubAccountListV1Resp {
    /**
     * 
     * @type {Array<SubaccountGetSubAccountListV1RespSubAccountsInner>}
     * @memberof SubaccountGetSubAccountListV1Resp
     */
    'subAccounts'?: Array<SubaccountGetSubAccountListV1RespSubAccountsInner>;
}

